#    $$\      $$\           $$\       $$$$$$$\  $$\                     $$\
#    $$ | $\  $$ |          $$ |      $$  __$$\ $$ |                    \__|
#    $$ |$$$\ $$ | $$$$$$\  $$$$$$$\  $$ |  $$ |$$ |$$\   $$\  $$$$$$\  $$\ $$$$$$$\
#    $$ $$ $$\$$ |$$  __$$\ $$  __$$\ $$$$$$$  |$$ |$$ |  $$ |$$  __$$\ $$ |$$  __$$\
#    $$$$  _$$$$ |$$$$$$$$ |$$ |  $$ |$$  ____/ $$ |$$ |  $$ |$$ /  $$ |$$ |$$ |  $$ |
#    $$$  / \$$$ |$$   ____|$$ |  $$ |$$ |      $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |  $$ |
#    $$  /   \$$ |\$$$$$$$\ $$$$$$$  |$$ |      $$ |\$$$$$$  |\$$$$$$$ |$$ |$$ |  $$ |
#    \__/     \__| \_______|\_______/ \__|      \__| \______/  \____$$ |\__|\__|  \__|
#                                                             $$\   $$ |
#                                                             \$$$$$$  |
#                                                              \______/
Settings:
  HTMLPORT: 25567
  PHPPort: 25568
  ServerIP: localhost #Used for both PHP and HTML
  debug: false #Only enable if I need debug logs.
  EnablePHP: false
  EnableHTML: true
  Autokey: false #Don't enable as it's still WIP.

SSLSettings: #jks key required!
  EnableSSL: false
  SSLPort: 25570
  SSLJKSName: filename #Without .jks
  SSLJKSPass: filepass
  SSLJKSKey: filekey
###
# While the self-signed key is nice and all I do recommend a lets-encrypt cert.
# Read about how to make one and convert it from .pem to .jks here:
# https://ordina-jworks.github.io/security/2019/08/14/Using-Lets-Encrypt-Certificates-In-Java.html#installing-a-lets-encrypt-certificate
###


#DO NOT IN ANY WAY EDIT THIS
ConfigVersion: 8