#    $$\      $$\           $$\       $$$$$$$\  $$\                     $$\
#    $$ | $\  $$ |          $$ |      $$  __$$\ $$ |                    \__|
#    $$ |$$$\ $$ | $$$$$$\  $$$$$$$\  $$ |  $$ |$$ |$$\   $$\  $$$$$$\  $$\ $$$$$$$\
#    $$ $$ $$\$$ |$$  __$$\ $$  __$$\ $$$$$$$  |$$ |$$ |  $$ |$$  __$$\ $$ |$$  __$$\
#    $$$$  _$$$$ |$$$$$$$$ |$$ |  $$ |$$  ____/ $$ |$$ |  $$ |$$ /  $$ |$$ |$$ |  $$ |
#    $$$  / \$$$ |$$   ____|$$ |  $$ |$$ |      $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |  $$ |
#    $$  /   \$$ |\$$$$$$$\ $$$$$$$  |$$ |      $$ |\$$$$$$  |\$$$$$$$ |$$ |$$ |  $$ |
#    \__/     \__| \_______|\_______/ \__|      \__| \______/  \____$$ |\__|\__|  \__|
#                                                             $$\   $$ |
#                                                             \$$$$$$  |
#                                                              \______/
Settings:
  HTMLPORT: 25567
  PHPPort: 25568
  ServerIP: localhost #Used for both PHP and HTML
  debug: false #Only enable if I need debug logs.
  EnablePHP: false
  EnableHTML: true
  Autokey: false #Don't enable as it's still WIP.

SSLSettings: #PEM Key required!
  EnableSSL: false
  SSLPort: 25570
  SSLDomain: domain.com
  SSLPriv: private-key.pem
  SSLPubl: public-key.pem
Linuxphpsettings:
  Errorfolder: /errors/


#DO NOT IN ANY WAY EDIT THIS
ConfigVersion: 11