# ==============================
# 🔧 WebPluginV2 Configuration
# Author: JumpWatch
# Discord support: https://discord.gg/9HDFz9vyv4
# ==============================

Settings:
  # ── Web Server Ports ──
  HTMLPORT: 25567
  PHPPort: 25568
  LocalFPM: 25569         # Very important if you decide to use PHP.

  # ── Server Settings ──
  ServerLocation: /home/container/   # Include trailing slash.
  IndexLocation: ""                  # Default: "" = /webplugin/php/
  ServerIP: localhost                # Used for PHP and HTML via /webp command.

  # ── Threading ──
  maxThreads: 2

  # ── Debug Settings ──
  debug: false                       # Shows debug log in /webplugin/logs/.

  # ── PHP Settings ──
  EnablePHP: false
  PHPFolderPermissionFix: false       # Runs `chown -R www-data`, auto disables after run.
  # ── Dependencies Reminder ──
  # IMPORTANT: If PHP is enabled, the plugin WILL automatically download
  # critical system libraries (GLIBC, LIBONIG, LIBZ) from the GitHub repo.
  # These libraries are essential for the system to work, and are required
  # for PHP, NGINX (Which is also downloaded from the repo),
  # and other components to function properly.
  # Check further down for info.

  # ── HTML Settings ──
  EnableHTML: true                  # PHP can also serve HTML.

  # ── Auto Key ──
  Autokey: false                     # Not functional currently.

  # ── NGINX Configuration ──
  denyNginxConfigOverride: false

# ── SSL Configuration ──
SSLSettings:
  EnableSSL: false
  SSLPort: 25570
  SSLDomain: play.domain.com
  SSLPriv: priv-key.pem
  SSLPubl: pub-key.pem

# ── Linux PHP Runtime Settings ──
Linuxphpsettings:
  Errorfolder: /errors/            #UNUSED


# ── GitHub Repo Resources ──
GithubWebPluginPHPRepo: https://github.com/hypersmc/WebPluginV2Repo
GithubWebPluginPHPRepoFilename: WebPlugin-linux-PHP8.3-PRECOMPILED.tar.gz
GithubWebPluginNGINXRepoFilename: WebPlugin-linux-NGINX-1.27.1-PRECOMPILED.tar.gz

# ── Internal ──
ConfigVersion: 15                  # DO NOT EDIT
