#                    ██╗    ██╗███████╗██████╗ ██████╗ ██╗     ██╗   ██╗ ██████╗ ██╗███╗   ██╗
#                    ██║    ██║██╔════╝██╔══██╗██╔══██╗██║     ██║   ██║██╔════╝ ██║████╗  ██║
#                    ██║ █╗ ██║█████╗  ██████╔╝██████╔╝██║     ██║   ██║██║  ███╗██║██╔██╗ ██║
#                    ██║███╗██║██╔══╝  ██╔══██╗██╔═══╝ ██║     ██║   ██║██║   ██║██║██║╚██╗██║
#                    ╚███╔███╔╝███████╗██████╔╝██║     ███████╗╚██████╔╝╚██████╔╝██║██║ ╚████║
#                     ╚══╝╚══╝ ╚══════╝╚═════╝ ╚═╝     ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝╚═╝  ╚═══╝
#    ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ ██╗   ██╗██████╗  █████╗ ████████╗██╗ ██████╗ ███╗   ██╗
#    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ ██║   ██║██╔══██╗██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║
#    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗██║   ██║██████╔╝███████║   ██║   ██║██║   ██║██╔██╗ ██║
#    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║██║   ██║██╔══██╗██╔══██║   ██║   ██║██║   ██║██║╚██╗██║
#    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝╚██████╔╝██║  ██║██║  ██║   ██║   ██║╚██████╔╝██║ ╚████║
#    ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
Settings:
  HTMLPORT: 25567
  PHPPort: 25568
  ServerIP: localhost #Used for both PHP and HTML
  debug: false #Only enable if I need debug logs.
  EnablePHP: false
  EnableHTML: true

SSLSettings: #Headsup. For now the only way to get an ssl key is to use JKS (Keystore) This system is still very early and might not even work.
  EnableSSL: false
  SSLPort: 25570
  SSLJKSName: "filename" #Without .jks
  SSLJKSPass: "filepass"
  SSLJKSKey: "filekey"
###To create an .jks key follow this
# https://docs.oracle.com/cd/E19509-01/820-3503/ggfen/index.html
###Be sure you do it right otherwise it wont work!


#DO NOT IN ANY WAY EDIT THIS
ConfigVersion: 5