name: webplugin
main: me.jumpwatch.webserver.WebCore
version: 2.8R
api-version: 1.13
folia-supported: true
description: Adds the ability to have an integrated webserver for your minecraft server.
author: JumpWatch, HypersMC, HumpJump
libraries:
  - org.eclipse.jetty:jetty-server:10.0.22
  - org.eclipse.jetty:jetty-servlet:10.0.22
  - org.shredzone.acme4j:acme4j-client:3.3.1
  - org.shredzone.acme4j:acme4j-it:3.3.1
  - org.shredzone.acme4j:acme4j-smime:3.3.1
  - org.shredzone.acme4j:acme4j-utils:2.16
commands:
  WebP:
    description: Gets IP or Domain W/ Port
    usage: /<command>
